services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn booker.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./booker:/booker/booker
      - ./alembic.ini:/booker/alembic.ini
      - ./setup.py:/booker/setup.py
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://fastapi_user:fastapi_pass@db:5432/fastapi_db
    depends_on:
      - db

volumes:
  postgres_data: